### ISSUE TITLE
Overlay Control Changes

### ISSUE THREAD

**Issue by RobbieDubya** [Workshop12/HeadUnit#104]
With the overlays - the entire rectangle captures all touch - the controls under them don’t receive any events event if they’re transparent. @tneil is the bottom one too tall on the tablet?

Intend on:
1. Making overlays invisible until touched.
2. Making overlays not trigger until dragged far enough

**Comment by tneil** [comment]
Yeah, based on your description it's too tall on the tablet. It covers pretty much the whole play/skip/prev controls in Google Play Music

On May 9, 2018 11:02 PM, Rob Williams Jnr <notifications@github.com> wrote:

With the overlays - the entire rectangle captures all touch - the controls under them don’t receive any events event if they’re transparent. @tneil<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftneil&data=02%7C01%7C%7C17d235f9bb384e7bac9708d5b6226535%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636615181196023331&sdata=TekwFVaO5AJAz0LS8%2B9XuBDlc6PakFSeOFvwZ187ZVc%3D&reserved=0> is the bottom one too tall on the tablet?

Intend on:

  1.  Making overlays invisible until touched.
  2.  Making overlays not trigger until dragged far enough

**Comment by RobbieDubya** [comment]
Have a play with the height of the home control here:
https://github.com/Workshop12/HeadUnit/blob/c11233b9bce8ba9debaaafc519db37be4cc9d53c/java/experimental/PureViews/app/src/main/java/com/williwoodstudios/pureviews/overlay/OverlayTargetView.java#L61
