### ISSUE TITLE
Clock Time display incorrect

### ISSUE THREAD

**Issue by tneil** [Workshop12/HeadUnit#106]
When it is 12 **pm or am** the clock displays as **0:00**.  I looked at the formatting code but couldn't quite figure out what was going on.

When the clock displays two first digits "10, 11" the minutes displayed are cut off on the right hand side of the screen.  I think we just need move it over to the left by a couple of pixels

**Comment by RobbieDubya** [comment]
Lots of this placement was so that it looked good on the 7" in Alex's car.
