### ISSUE TITLE
Insert/Remove Relay app instead of generating grid

### ISSUE THREAD

**Issue by tneil** [Workshop12/HeadUnit#145]
Currently turning on/off the relay app takes a long time as we are re-building the entire app grid.  Need to just insert and remove it from the list.

**Comment by tneil** [comment]
This is going to be a fairly major overhaul of how we are generating the app grid.  When we call getItems() from the menu configuration it is going out and grabbing all app icons.  This would have to change.  Needs more work and isn't critical for version 2

**Comment by RobbieDubya** [comment]
Took a different approach - made the menu items capable of changing visibility.

**Comment by tneil** [comment]
Cool.. I was thinking about that also, but then thought "fuck it" LOL
