### ISSUE TITLE
Navigation Bar circles have 3 o'clock line

### ISSUE THREAD

**Issue by RobbieDubya** [Workshop12/HeadUnit#150]
Navigation bar circles are being rendered with line at 3 o'clock.

(Circle drawing code hasn't changed since 2015)

**Comment by RobbieDubya** [comment]
Current: ![image](https://user-images.githubusercontent.com/1776104/47405718-effc1300-d720-11e8-8482-a18039365562.png)

New: 
![image](https://user-images.githubusercontent.com/1776104/47405766-22a60b80-d721-11e8-9731-d884eaf23dea.png)

**Comment by tneil** [comment]
Fixed
