### ISSUE TITLE
Font Size in Relay Input Boxes

### ISSUE THREAD

**Issue by tneil** [Workshop12/HeadUnit#152]
For whatever reason, on the different resolutions the font size will seem huge or smaller.  Right now the text size is being set to height/2.

This looks good on the low resolution devices, but looks huge on the high resolution devices.  But it should be proportional so I don't understand why it is growing so large on the higher res devices??

**Comment by RobbieDubya** [comment]
Text height now proportional to row height.

![image](https://user-images.githubusercontent.com/1776104/47536772-0674ac80-d890-11e8-9aba-d7a52fbd6717.png)
