### ISSUE TITLE
Wedge Screen Push Causes Endless Loop

### ISSUE THREAD

**Issue by tneil** [Workshop12/HeadUnit#158]
When I try and push one of the Wedge screens (WedgeSpinnerScreen) the app goes into an endless loop.

stack=java.lang.StackOverflowError: stack size 8MB
at com.williwoodstudios.pureviews.BrainiacLayout.pushScreen(BrainiacLayout.java:224)
at com.williwoodstudios.pureviews.AppSpace.pushScreen(AppSpace.java:78)

I'm trying to use a wedge screen as a confirm for Uninstall/Hide option on a long press of an app on the grid

**Comment by tneil** [comment]
Currently I have a long press on the app icon to toggle it's hidden state.

**Comment by RobbieDubya** [comment]
Created a confirmation wedge with simple question|y|n.
